/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /var/services/homes/spparmar/spec2006/tools/src/perl-5.8.7/miniperl ../bin/enc2xs -Q -O -o byte_t.c -f byte_t.fnm
*/
extern encode_t AdobeStandardEncoding_encoding;
extern encode_t MacCentralEurRoman_encoding;
extern encode_t MacRoman_encoding;
extern encode_t MacSami_encoding;
extern encode_t cp1250_encoding;
extern encode_t cp1252_encoding;
extern encode_t cp1254_encoding;
extern encode_t cp1257_encoding;
extern encode_t cp1258_encoding;
extern encode_t cp437_encoding;
extern encode_t cp775_encoding;
extern encode_t cp850_encoding;
extern encode_t cp852_encoding;
extern encode_t cp857_encoding;
extern encode_t cp860_encoding;
extern encode_t cp861_encoding;
extern encode_t cp862_encoding;
extern encode_t cp863_encoding;
extern encode_t cp865_encoding;
extern encode_t gsm0338_encoding;
extern encode_t hp_roman8_encoding;
extern encode_t iso_8859_2_encoding;
extern encode_t iso_8859_3_encoding;
extern encode_t iso_8859_4_encoding;
extern encode_t iso_8859_5_encoding;
extern encode_t iso_8859_6_encoding;
extern encode_t iso_8859_7_encoding;
extern encode_t iso_8859_8_encoding;
extern encode_t iso_8859_9_encoding;
extern encode_t iso_8859_10_encoding;
extern encode_t iso_8859_11_encoding;
extern encode_t iso_8859_13_encoding;
extern encode_t iso_8859_14_encoding;
extern encode_t iso_8859_15_encoding;
extern encode_t iso_8859_16_encoding;
extern encode_t nextstep_encoding;
extern encode_t viscii_encoding;
