C        DUMMY ROUTINES
C
      SUBROUTINE OLIXMAIN
      WRITE(6,*) 'NO TDHFX CODE'
      CALL ABRT
      RETURN
      END
C
      INTEGER FUNCTION IGETOLI(N)
      IF(N.EQ.27972) CALL ABRT
      IGETOLI=0
      RETURN
      END
C
      SUBROUTINE SVGGA1(X,NFT18)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(NFT18.NE.18) X=12.345D+00
      RETURN
      END
C
      SUBROUTINE SVGGA2(EIG,C,YA,NROT,WRK1,WRK2,DTEMP,FTEMP,NUM2,
     *                  GHONDO,XINTS,DSH,DDIJ,XX,IX,MAXG,NSH2,MXG2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(MXG2.LT.0) THEN
          ISUM = NROT + NUM2+MAXG+NSH2+IX
          SUM = EIG+C+YA+WRK1+WRK2+DTEMP+FTEMP+GHONDO+XINTS+DSH+DDIJ+XX
          WRITE(6,*) ISUM,SUM
      END IF
      RETURN
      END
C
      SUBROUTINE SVGSA(DSAO,DSMO,C,T)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(C.EQ.-1234.5D+11) THEN
          SUM = DSAO+DSMO+T
          WRITE(6,*) SUM
      END IF
      RETURN
      END
C
      SUBROUTINE SVGFNM(FREQ,VEC,NC1,LINEAR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL LINEAR
      IF(NC1.LT.-123) THEN
          SUM = FREQ+VEC
          IF(LINEAR) WRITE(6,*) SUM
      END IF
      RETURN
      END
C
      SUBROUTINE ADDFOE(X,IAT,JAT,FOE,FAC,TWO)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(TWO.EQ.-1234.5D+11) THEN
          SUM = X+FOE+FAC+IAT+JAT
          WRITE(6,*) SUM
      END IF
      RETURN
      END
C
      SUBROUTINE TDXDELETE(IADDRESS,LENGTH)
      IF(LENGTH.LT.0) IADDRESS=158
      RETURN
      END
C
      SUBROUTINE NEW(IADDRESS,LENGTH)
      IF(LENGTH.LT.0) IADDRESS=158
      RETURN
      END
C
      SUBROUTINE SVGFDD(FDD,NXYZ2,NAT,L2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(L2.LT.0) THEN
          SUM = FDD+NXYZ2+NAT
          WRITE(6,*) SUM
      END IF
      RETURN
      END
C
      SUBROUTINE SVGSDD(SDD,NXYZ2,NAT,L2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(L2.LT.0) THEN
          SUM = SDD+NXYZ2+NAT
          WRITE(6,*) SUM
      END IF
      RETURN
      END
C
      SUBROUTINE SYMFDD(FDD,NUM,NAT,L2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      IF(L2.LT.0) THEN
          SUM = FDD+NUM+NAT
          WRITE(6,*) SUM
      END IF
      RETURN
      END
C
      SUBROUTINE CHECKFIELDS(BFLDX,BFLDY,BFLDZ)
      LOGICAL BFLDX,BFLDY,BFLDZ
      IF(BFLDX .AND. BFLDY .AND. BFLDZ) WRITE(6,*) 'ALL TRUE'
      RETURN
      END
C
C--      SUBROUTINE DERIOLI(DXXDI,DYYDI,DZZDI,XX,YY,ZZ,LIT,LJT,AI)
C--      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C--      DOUBLE PRECISION DXXDI(6,6),DYYDI(6,6),DZZDI(6,6),
C--     *                 XX(6,6),YY(6,6),ZZ(6,6),AI
C--      IF(AI.EQ.12345D+11) THEN
C--          SUM = DXXDI(1,1)+DYYDI(1,1)+DZZDI(1,1)+XX(1,1)+YY(1,1)+ZZ(1,1)
C--          WRITE(6,*) SUM,LIT+LJT
C--      END IF
C--      RETURN
C--      END
C
      SUBROUTINE DERIOLI(DXDI,DYDI,DZDI,X,Y,Z,LIT,LJT,AI)
      IMPLICIT NONE
      DOUBLE PRECISION X(6,6),Y(6,6),Z(6,6)
      DOUBLE PRECISION DXDI(6,6),DYDI(6,6),DZDI(6,6)
      INTEGER LIT,LJT
      DOUBLE PRECISION AI
      INTEGER I,J
C
C     ----- DXDI ... -----
C
      DO 110 J=1,LJT
        DXDI(1,J)=X(2,J)*(AI+AI)
        DYDI(1,J)=Y(2,J)*(AI+AI)
        DZDI(1,J)=Z(2,J)*(AI+AI)
  110 CONTINUE
C
      IF(LIT.EQ.1) RETURN
C
      DO 120 I=2,LIT
        DO 120 J=1,LJT
          DXDI(I,J)=X(I+1,J)*(AI+AI) - X(I-1,J)*(I-1)
          DYDI(I,J)=Y(I+1,J)*(AI+AI) - Y(I-1,J)*(I-1)
          DZDI(I,J)=Z(I+1,J)*(AI+AI) - Z(I-1,J)*(I-1)
  120 CONTINUE
      RETURN
      END
C
      SUBROUTINE DERJOLI(DXXDJ,DYYDJ,DZZDJ,XX,YY,ZZ,LIT,LJT,AJ)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION DXXDJ(6,6),DYYDJ(6,6),DZZDJ(6,6),
     *                 XX(6,6),YY(6,6),ZZ(6,6),AJ
      IF(AJ.EQ.12345D+11) THEN
          SUM = DXXDJ(1,1)+DYYDJ(1,1)+DZZDJ(1,1)+XX(1,1)+YY(1,1)+ZZ(1,1)
          WRITE(6,*) SUM,LIT+LJT
      END IF
      RETURN
      END
