#
# Makefile for SPEC's hacked up md5sum
# Copyright (C) 1996-2003 Standard Performance Evaluation Corporation
#
# $Id: Makefile.nt 3222 2005-10-05 19:51:58Z cloyce $

all: libtu.lib

CC=cl
CFLAGS=/Ox -I.. -I. -DHAVE_CONFIG_H -D__STDC__
LDFLAGS=/Ox

LIBOBJS=long-options.obj error.obj getline.obj getopt.obj getopt1.obj md5.obj strtoull.obj xmalloc.obj

libtu.lib: $(LIBOBJS)
	lib /out:$@ /subsystem:console $(LIBOBJS)

cleanobjs:
	del *.obj libtu.lib

clean:
	del *.obj md5sum.exe config.h *.pdb libtu.lib

distclean: clean
