# Tar makefile for Windows NT
#   Geoff Voelker (voelker@cs.washington.edu)
#
# Copyright (C) 1993 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

.silent:

!include <ntwin32.mak>

#
# definitions
# 
RM	      = del /q

DEFS	      = -DNONAMES -DNO_REMOTE -DSTDC_HEADERS=1 \
		-DWINDOWSNT -DUSE_PROTOTYPES -DHAVE_FTIME \
		-DHAVE_MKDIR -DHAVE_GETCWD -DNO_REMOTE \
		-DHAVE_STRSTR -DHAVE_RENAME -DDEFBLOCKING=2

INCDIRS	      = -I.

LIBS	      = $(conlibs) setargv.obj

OBJS 	      = tar.obj create.obj extract.obj buffer.obj \
		getoldopt.obj update.obj gnu.obj mangle.obj \
		version.obj list.obj names.obj diffarch.obj \
		port.obj fnmatch.obj getopt.obj getopt1.obj \
		regex.obj getdate.obj alloca.obj wnt_dir.obj

#
# everything in this directory
#
all:		tar.exe

#
# tar
#
tar.exe:	testpad.h getdate.c $(OBJS)
		$(RM) testpad.obj
		$(link) $(linkdebug) $(conflags) -out:$@ $(OBJS) $(LIBS)
#
# testpad
#
testpad.h: 	testpad.exe
		testpad

testpad.exe:	testpad.obj
		$(link) $(linkdebug) $(conflags) -out:$@ testpad.obj $(LIBS)
#
# source to object
#
.c.obj:;	$(cc) $(DEFS) $(INCDIRS) -Ox $(cflags) $(cvars) $<


clean:;		$(RM) errs *.obj *~ tar.exe testpad.exe testpad.h

mostlyclean: 	clean
distclean: 	clean
realclean: 	clean
