#
# Makefile for SPEC's hacked up md5sum
# Copyright (C) 1996-2003 Standard Performance Evaluation Corporation
#
# $Id: Makefile.nt 3222 2005-10-05 19:51:58Z cloyce $

all: specmd5sum.exe

CC=cl
CFLAGS=/Ox -I. -Ilib -Iwin32 -DHAVE_CONFIG_H -D__STDC__
LDFLAGS=/Ox

config.h: config.h.win32
	copy config.h.win32 config.h
md5sum.obj: config.h md5sum.c
win32\dirent.obj: config.h win32\dirent.c
lib/libtu.lib:
	cd lib
	$(MAKE) /f Makefile.nt
	cd ..

specmd5sum.exe: md5sum.obj lib\libtu.lib win32\dirent.obj
	$(CC) $(LDFLAGS) -Fe$@ md5sum.obj lib\libtu.lib dirent.obj

cleanobjs:
	del *.obj lib\*.obj
	cd lib
	$(MAKE) /f Makefile.nt cleanobjs
	cd ..

clean:
	del *.obj specmd5sum.exe config.h *.pdb
	cd lib
	$(MAKE) /f Makefile.nt clean
	cd ..

distclean: clean
