/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
static yyconst short int yy_acclist[234] =
    {   0,
       44,   39,   42,   43,   41,   42,   43,   40,   43,   42,
       43,    1,   42,   43,   39,   42,   43,   39,   42,   43,
       39,   42,   43,    2,   42,   43,   40,   42,   43,   39,
       42,   43,   39,   42,   43,   39,   42,   43,   39,   42,
       43,   39,   42,   43,   40,   43,   39,   42,   43,    9,
       43,    8,   43,    9,   43,    4,    9,   43,    3,    9,
       43,   39,   10,   39,   39,   39,   39,   39,   39,   39,
       39,   37,   39,   39,   39,   39,   39,   39,   11,    5,
       39,   39,   39,   27,   39,   39,   39,   39,   39,   39,
       33,   39,   39,   39,   38,   39,   39,   39,   39,   39,

       16,   39,    6,   27,   39,   39,   39,   39,   39,   39,
       39,   39,   33,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   28,   39,
       29,   39,   39,   39,   39,   39,   39,   39,   34,   39,
       35,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   28,   29,   39,   30,   39,   25,   39,
       39,   39,   23,   39,   34,   35,   39,   36,   39,   31,
       39,   39,   39,   24,   39,   39,   39,   39,   39,   39,
       20,   39,   30,   25,   23,   21,   39,   26,   39,   39,
       36,   31,   24,   22,   39,   32,   39,   39,   39,   39,

       39,   15,   39,   39,    7,   21,   26,   12,   39,   22,
       32,   13,   39,   39,   39,   39,   39,   12,   13,   14,
       39,   39,   19,   39,   18,   39,   14,   19,   39,   39,
       17,   39,   17
    } ;

static yyconst short int yy_accept[271] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    8,   10,   12,   15,   18,   21,   24,
       27,   30,   33,   36,   39,   42,   45,   47,   50,   52,
       54,   56,   59,   62,   63,   63,   64,   64,   65,   66,
       67,   68,   68,   69,   70,   71,   72,   72,   73,   74,
       75,   76,   77,   78,   78,   79,   79,   80,   80,   81,
       81,   81,   81,   81,   82,   83,   84,   86,   87,   88,
       88,   88,   88,   88,   89,   90,   91,   93,   94,   95,
       95,   96,   96,   97,   98,   99,  100,  101,  103,  103,
      103,  104,  104,  104,  104,  105,  105,  105,  106,  107,

      108,  109,  110,  111,  112,  113,  113,  113,  113,  114,
      114,  114,  115,  116,  117,  118,  119,  120,  121,  122,
      122,  123,  123,  124,  125,  126,  127,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  129,  131,  133,
      134,  135,  136,  137,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  139,  141,  143,  144,  145,  146,  147,
      148,  148,  149,  149,  149,  150,  151,  152,  153,  154,
      154,  154,  155,  156,  156,  156,  156,  156,  156,  157,
      159,  161,  162,  163,  165,  165,  166,  167,  167,  167,
      167,  167,  167,  168,  170,  172,  173,  174,  176,  176,

      177,  177,  177,  178,  179,  180,  181,  183,  183,  183,
      184,  185,  185,  185,  186,  188,  190,  191,  191,  192,
      193,  193,  193,  194,  196,  198,  199,  199,  200,  200,
      200,  201,  202,  204,  205,  206,  207,  208,  208,  210,
      211,  212,  212,  214,  214,  215,  215,  215,  216,  217,
      218,  219,  220,  220,  222,  222,  222,  223,  225,  227,
      228,  228,  229,  230,  230,  231,  231,  233,  234,  234
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    1,   10,   11,    1,
        1,   12,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   13,    1,
        1,    1,   14,    1,   15,    1,   16,   17,   18,   19,
        1,    1,   20,    1,    1,   21,   22,   23,   24,    1,
        1,   25,   26,   27,   28,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   15,    1,   16,   17,

       18,   19,    1,    1,   20,    1,    1,   21,   22,   23,
       24,    1,    1,   25,   26,   27,   28,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[29] =
    {   0,
        1,    2,    2,    3,    2,    3,    3,    1,    1,    1,
        3,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[276] =
    {   0,
        0,    0,    0,    0,  332,   26,   29,   34,   43,   44,
      334,    0,  336,  336,  330,  336,   53,   80,   28,  336,
      336,  318,  308,  307,  305,  302,  322,  107,  336,  321,
       54,  336,  336,    0,  322,  336,  119,  306,   13,   29,
      300,  146,  304,   39,   42,  298,   61,   67,   73,  303,
       52,  302,  300,  312,  173,  313,  336,   81,   85,  297,
       53,   69,  291,  294,   15,  295,   79,  295,  293,  291,
       68,   80,  285,  288,   81,  289,   99,  289,  287,  121,
      336,  123,  280,  110,  281,  283,  272,    0,  294,  136,
      336,  279,  107,  280,  112,  280,  278,  274,  274,  274,

      271,  272,  272,  267,  269,  267,  114,  268,  127,  268,
      266,  262,  262,  262,  259,  260,  260,  255,  257,  251,
      257,  137,  249,  247,  242,  244,  247,  262,  246,  246,
      246,  243,  244,  244,  239,  241,  235,    0,    0,  238,
      237,  237,  226,  234,  232,  232,  232,  229,  230,  230,
      225,  227,  221,    0,    0,  224,  223,  223,  212,  220,
      222,  216,  213,  211,  207,  216,  215,  212,  212,  224,
      205,  336,  336,  208,  207,  207,  196,  204,  204,    0,
        0,  202,  203,    0,  196,  336,  336,  199,  198,  198,
      187,  195,  195,    0,    0,  193,  194,    0,  189,  181,

      181,  190,  188,  177,  186,  188,    0,    0,  184,  336,
      336,  181,  168,  336,    0,    0,  165,  164,  336,  336,
      162,  156,  336,    0,    0,  154,  143,  153,  151,  140,
      142,  144,    0,  146,  336,  336,  336,  143,    0,  336,
      336,  142,    0,  141,  138,  130,  133,  134,  134,  131,
      336,  336,  127,    0,  100,   99,   91,    0,    0,  336,
       90,  336,   88,   78,   62,   49,    0,  336,  336,  186,
       48,  189,  192,  195,  198
    } ;

static yyconst short int yy_def[276] =
    {   0,
      269,    1,    1,    1,    1,    1,  270,  270,  270,  270,
      269,  271,  269,  269,  272,  269,  271,  271,  271,  269,
      269,  271,  271,  271,  271,  271,  269,  273,  269,  269,
      269,  269,  269,  271,  272,  269,  269,  271,  271,  271,
      271,  269,  271,  271,  271,  271,  269,  269,  271,  271,
      271,  271,  271,  269,  273,  274,  269,  269,  269,  269,
      269,  269,  269,  271,  271,  271,  271,  271,  271,  269,
      269,  269,  269,  271,  271,  271,  271,  271,  271,  269,
      269,  269,  271,  271,  271,  271,  271,  271,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  271,  271,  271,

      271,  271,  271,  271,  271,  269,  269,  269,  269,  269,
      269,  271,  271,  271,  271,  271,  271,  271,  271,  269,
      271,  269,  271,  271,  271,  271,  271,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  271,  271,  271,  271,
      271,  271,  271,  271,  269,  269,  269,  269,  269,  269,
      269,  269,  271,  271,  271,  271,  271,  271,  271,  271,
      269,  271,  269,  269,  271,  271,  271,  271,  271,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  271,  271,
      271,  271,  271,  271,  269,  269,  269,  269,  269,  269,
      269,  269,  271,  271,  271,  271,  271,  271,  269,  271,

      269,  269,  271,  271,  271,  271,  271,  275,  269,  269,
      269,  269,  269,  269,  271,  271,  271,  269,  269,  269,
      269,  269,  269,  271,  271,  271,  269,  271,  269,  269,
      271,  271,  271,  271,  269,  269,  269,  269,  271,  269,
      269,  269,  271,  269,  271,  269,  269,  271,  271,  271,
      269,  269,  269,  271,  269,  269,  271,  271,  271,  269,
      269,  269,  271,  269,  271,  269,  271,  269,    0,  269,
      269,  269,  269,  269,  269
    } ;

static yyconst short int yy_nxt[365] =
    {   0,
       12,   13,   14,   13,   13,   15,   16,   17,   18,   19,
       20,   12,   21,   22,   12,   12,   12,   23,   12,   24,
       12,   25,   12,   12,   12,   12,   12,   26,   27,   47,
       48,   30,   47,   65,   99,   66,   30,   28,   31,   32,
      100,   28,   28,   31,   32,   30,   30,   67,   34,   33,
       33,   68,   31,   31,   37,   58,   59,   37,   58,   75,
       77,   76,   47,   48,   78,   47,  268,   85,   80,   38,
       39,   80,   40,   93,   82,   94,   81,   82,   86,  267,
       41,   42,   58,   59,   42,   58,   90,   95,  107,   90,
      108,   96,   83,  266,   91,  102,   43,   44,  109,   45,

      113,  103,  110,  265,  264,  263,  114,   46,   56,   57,
       56,   56,   56,   56,  122,  116,  262,   56,  261,   56,
       37,  117,   80,   37,   82,   80,  130,   82,  133,  123,
       81,  124,  131,  146,  134,   60,   61,   90,   62,  147,
       90,  122,  120,  149,  260,   91,   63,   42,  259,  150,
       42,  258,  257,  256,  255,  254,  163,  253,  164,  252,
      251,  250,   70,   71,  249,   72,  248,  247,  246,  245,
      244,  243,  242,   73,   56,   57,   56,   56,   56,   56,
      241,  240,  239,   56,  238,   56,   29,   29,   29,   35,
       35,   35,   55,   55,   55,   56,   56,   56,  235,  237,

      235,  236,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  148,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  132,  129,  128,  127,

      126,  125,  121,  119,  118,  115,  112,  111,  106,  105,
      104,  101,   98,   97,   92,   57,   89,   88,   87,   84,
       79,   74,   69,   64,   36,   54,   54,   53,   52,   51,
       50,   49,   36,  269,   27,   11,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269
    } ;

static yyconst short int yy_chk[365] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,   19,
       19,    7,   19,   39,   65,   39,    8,    6,    7,    7,
       65,    6,    6,    8,    8,    9,   10,   40,  271,    9,
       10,   40,    9,   10,   17,   31,   31,   17,   31,   44,
       45,   44,   47,   47,   45,   47,  266,   51,   48,   17,
       17,   48,   17,   61,   49,   61,   48,   49,   51,  265,
       17,   18,   58,   58,   18,   58,   59,   62,   71,   59,
       71,   62,   49,  264,   59,   67,   18,   18,   72,   18,

       75,   67,   72,  263,  261,  257,   75,   18,   28,   28,
       28,   28,   28,   28,   84,   77,  256,   28,  255,   28,
       37,   77,   80,   37,   82,   80,   93,   82,   95,   84,
       80,   84,   93,  107,   95,   37,   37,   90,   37,  107,
       90,  122,   82,  109,  253,   90,   37,   42,  250,  109,
       42,  249,  248,  247,  246,  245,  122,  244,  122,  242,
      238,  234,   42,   42,  232,   42,  231,  230,  229,  228,
      227,  226,  222,   42,   55,   55,   55,   55,   55,   55,
      221,  218,  217,   55,  213,   55,  270,  270,  270,  272,
      272,  272,  273,  273,  273,  274,  274,  274,  275,  212,

      275,  209,  206,  205,  204,  203,  202,  201,  200,  199,
      197,  196,  193,  192,  191,  190,  189,  188,  185,  183,
      182,  179,  178,  177,  176,  175,  174,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,
      124,  123,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  108,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   94,   92,   89,   87,

       86,   85,   83,   79,   78,   76,   74,   73,   70,   69,
       68,   66,   64,   63,   60,   56,   54,   53,   52,   50,
       46,   43,   41,   38,   35,   30,   27,   26,   25,   24,
       23,   22,   15,   11,    5,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
/* 
 * Copyright (C) 2000,2001 Erik Edelmann <eedelman@beam.helsinki.fi>
 *
 *     This program is free software;  you  can  redistribute  it
 *     and/or modify it under the terms of the GNU General Public
 *     License version 2 as published  by  the  Free  Software  
 *     Foundation.
 *
 *     This program is distributed in the hope that  it  will  be
 *     useful, but WITHOUT ANY WARRANTY; without even the implied
 *     warranty of MERCHANTABILITY or FITNESS  FOR  A  PARTICULAR
 *     PURPOSE.   See  the  GNU  General  Public License for more
 *     details.
 *
 *     You should have received a copy of the GNU General  Public
 *     License along with this program; if not, write to the Free
 *     Software Foundation, Inc., 59  Temple  Place,  Suite  330,
 *     Boston, MA  02111-1307  USA
 */


#include <string.h>
#include <errno.h>
#include <assert.h>
#include "global.h"
#include "errormesg.h"
#include "find_dep.h"
#include "xmalloc.h"

void yy_push_state(int new_state);
void yy_pop_state();
void pop_filestack ();

static bool in_interface = false;

static YY_BUFFER_STATE include_stack[INCLUDE_RECURSION_LIMIT];
static int line_num_stack[INCLUDE_RECURSION_LIMIT];
static int incl_buff = 0;

static char string_buf[MAX_STRING_LEN];
static char *string_buf_ptr;

static int old_startcond;


#define free_fmt 1
#define fixed_fmt 2

#define str_sq 3
#define str_dq 4


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 54 "lexer.l"




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 270 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 269 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 57 "lexer.l"
{ string_buf_ptr = string_buf; old_startcond = YY_START; 
                  BEGIN(str_dq); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "lexer.l"
{ string_buf_ptr = string_buf; old_startcond = YY_START; 
                  BEGIN(str_sq); }
	YY_BREAK
case 3:
#line 63 "lexer.l"
case 4:
YY_RULE_SETUP
#line 63 "lexer.l"
{ 
                    BEGIN(old_startcond);
                    *string_buf_ptr = '\0';
                    yylval.string = xstrdup (string_buf);
                    DEBUG_PRINT("string: '%s'\n", yylval.string);
                    return STRING;
                }
	YY_BREAK
case 5:
#line 72 "lexer.l"
case 6:
YY_RULE_SETUP
#line 72 "lexer.l"
/* Ignore (continued strings, free fmt) */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "lexer.l"
/*Ignore (cont. strings, fixed fmt) */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "lexer.l"
{ 
                    unput ('\n');
                    BEGIN(old_startcond);
                    yylval.number = yylineno;
                    return UNTERMINATED_STRING;
                }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "lexer.l"
{ *string_buf_ptr++ = yytext[0]; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return EOSTMT; } /* Treat comments like */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return EOSTMT; } /* empty lines */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return CPP_INCLUDE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return F90PPR_INCLUDE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return COCO_INCLUDE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return F_INCLUDE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return USE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "lexer.l"
{ in_interface = false; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "lexer.l"
{ in_interface = true; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 100 "lexer.l"
/* Ignore */
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "lexer.l"
{ if (!in_interface) return MODULE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return CPP_DEFINE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return F90PPR_DEFINE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return CPP_UNDEF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return F90PPR_UNDEF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return CPP_IFDEF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return CPP_IFNDEF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return CPP_IF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return CPP_ELIF; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return CPP_ELSE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return CPP_ENDIF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return F90PPR_IFDEF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return F90PPR_IFNDEF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return F90PPR_IF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return F90PPR_ELIF; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return F90PPR_ELSE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return F90PPR_ENDIF; }
	YY_BREAK
case 37:
#line 124 "lexer.l"
case 38:
YY_RULE_SETUP
#line 124 "lexer.l"
/* Ignore */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 127 "lexer.l"
{ yylval.string = xstrdup(yytext); return WORD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return EOSTMT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 131 "lexer.l"
/* Ignore */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return *yytext; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(free_fmt):
case YY_STATE_EOF(fixed_fmt):
case YY_STATE_EOF(str_sq):
case YY_STATE_EOF(str_dq):
#line 136 "lexer.l"
{ 
                    DEBUG_PRINT("EOF reached %i\n", incl_buff);
                    incl_buff--;
                    if (incl_buff < 0) {
                        incl_buff = 0;
                        yyterminate ();
                    } else {
                        yy_delete_buffer (YY_CURRENT_BUFFER);
                        yy_switch_to_buffer (include_stack[incl_buff]);
                        yylineno = line_num_stack[incl_buff];
                        pop_filestack ();
                    }
                }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 150 "lexer.l"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 270 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 270 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 269);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 150 "lexer.l"



bool lex_include_file (const char *incfile)
/* "Include" file 'incfile' here.  Return false for failure, true for success */
{
    FILE *bakup;

    DEBUG_PRINT("'%s'\n", incfile);

    if (incl_buff >= INCLUDE_RECURSION_LIMIT) {
        warning ("Recursion limit reached in file '%s'", incfile);
        return false;
    }

    bakup = yyin;
    yyin = fopen (incfile, "r");
    if (yyin == NULL) {
        if (errno == ENOENT) {
            if (options.warn)  warning ("Include file '%s' not found", incfile);
        } else
            warning ("Error reading file '%s', skipping", incfile);

        yyin = bakup;
        return false;
    }

    include_stack[incl_buff] = YY_CURRENT_BUFFER;
    yy_switch_to_buffer (yy_create_buffer (yyin, YY_BUF_SIZE));

    line_num_stack[incl_buff++] = yylineno;
    yylineno = 1;

    return true;
}


void lex_set_format (SourceFmt fmt)
{
    switch (fmt) {
        case UNKNOWN:
        case FREE: 
            BEGIN(free_fmt); break;
        case FIXED: 
            BEGIN(fixed_fmt); break;
        default: 
            assert(0);
    }
}


int yywrap ()
{
    return 1;
}
