/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Symbol.xs. Do not edit this file, edit Symbol.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#include <EXTERN.h>
#include <perl.h>
#include <XSUB.h>
#define U8 U8
#include "encode.h"
#include "symbol_t.h"

static void
Encode_XSEncoding(pTHX_ encode_t *enc)
{
 dSP;
 HV *stash = gv_stashpv("Encode::XS", TRUE);
 SV *sv    = sv_bless(newRV_noinc(newSViv(PTR2IV(enc))),stash);
 int i = 0;
 PUSHMARK(sp);
 XPUSHs(sv);
 while (enc->name[i])
  {
   const char *name = enc->name[i++];
   XPUSHs(sv_2mortal(newSVpvn(name,strlen(name))));
  }
 PUTBACK;
 call_pv("Encode::define_encoding",G_DISCARD);
 SvREFCNT_dec(sv);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Encode__Symbol); /* prototype to pass -Wmissing-prototypes */
XS(boot_Encode__Symbol)
{
    dXSARGS;

    XS_VERSION_BOOTCHECK ;


    /* Initialisation Section */

{
#include "symbol_t.exh"
}


    /* End of Initialisation Section */

    XSRETURN_YES;
}

