/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /var/services/homes/spparmar/spec2006/tools/src/perl-5.8.7/miniperl ../bin/enc2xs -Q -O -o symbol_t.c -f symbol_t.fnm
*/
extern encode_t AdobeSymbol_encoding;
extern encode_t AdobeZdingbat_encoding;
extern encode_t MacDingbats_encoding;
extern encode_t MacSymbol_encoding;
extern encode_t dingbats_encoding;
extern encode_t symbol_encoding;
